# Generated by Django 4.2.16 on 2024-11-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='tg_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='post',
        ),
    ]
