# Generated by Django 4.2.16 on 2024-11-27 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_first_name_users_tg_id_remove_users_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AddField(
            model_name='tasks',
            name='tg_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.users'),
            preserve_default=False,
        ),
    ]
