# Generated by Django 4.2.16 on 2024-11-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_users_name_tasks_tg_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='tg_id',
            new_name='tg',
        ),
    ]
