# Generated by Django 4.2.16 on 2024-11-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_rename_tg_id_tasks_tg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='tg_id',
            new_name='tg',
        ),
    ]
